version: '3.1'

services:

  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd123

  portservice:
    image: fafg/portservice:latest
    restart: always
    depends_on:
      - "mongo"
    links:
      - "mongo:database"
    ports:
      - 7070:7070
    environment:
      PORT_SERVICE_CONN_STR_DB: "mongodb://root:pwd123@database:27017/?authSource=admin&readPreference=primary&appname=airportgrpc&ssl=false&retryWrites=true"

  clientapi:
    image: fafg/clientapi:latest
    restart: always
    depends_on:
      - "portservice"
    links:
      - "portservice:portservice"
    ports:
      - 8080:8000
    volumes:
      #do not add the file name here, only the path
      - /path/to/your/json/file/:/go/file/
    environment:
      FILE_FOLDER_PATH: "/go/file/"
      PORT_SERVICE_ENDPOINT: "portservice:7070"