version: '3.1'

services:

  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd123

  portservice:
    image: fafg/portservice:latest
    restart: always
    depends_on:
      - "mongo"
    ports:
      - 7070:7070
    environment:
      PORT_SERVICE_CONN_STR_DB: "mongodb://root:pwd123@127.0.0.1:27017/?authSource=admin&readPreference=primary&appname=airportgrpc&ssl=false&retryWrites=true"

  clientapi:
    image: fafg/clientapi:latest
    restart: always
    depends_on:
      - "portservice"
    ports:
      - 8080:8080