debug:
	@ echo "cleaning..."
	@ rm -f pulumi-task
	@ echo "building..."
	@ go build -o pulumi-task main.go
	@ ls -lah pulumi-task
	@ echo "hurry up and attach the process(pulumi-task) to the debug session"
	@ echo "running..."
	@ pulumi up