name: Go-Docker-Example

on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ README.md ]
    
jobs:
  portservice:
    name: Port Service
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Port Service - Build
      shell: bash
      working-directory: ./portservice
      run: |
        make build-debug

    - name: Port Service - Test
      shell: bash
      working-directory: ./portservice
      run: |
        make test

    - name: Port Service - Docker Build & Push
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "./portservice/Dockerfile"
        BUILD_PATH: "./portservice"
        IMAGE_NAME: "fafg/portservice"
        TAG_NAME: "v0.0.1"
        LATEST: "true"